"""add_session_sharing_fields

Revision ID: 3e52890811d2
Revises: e000e43a0bf6
Create Date: 2025-07-06 02:15:07.883363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e52890811d2'
down_revision: Union[str, Sequence[str], None] = 'e000e43a0bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_sessions', sa.Column('invite_code', sa.String(length=6), nullable=True))
    op.add_column('translation_sessions', sa.Column('invite_expires_at', sa.DateTime(), nullable=True))
    op.add_column('translation_sessions', sa.Column('guest_access_token', sa.Text(), nullable=True))
    op.add_column('translation_sessions', sa.Column('allow_guest_access', sa.Boolean(), nullable=True))
    op.add_column('translation_sessions', sa.Column('max_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_sessions', 'max_participants')
    op.drop_column('translation_sessions', 'allow_guest_access')
    op.drop_column('translation_sessions', 'guest_access_token')
    op.drop_column('translation_sessions', 'invite_expires_at')
    op.drop_column('translation_sessions', 'invite_code')
    # ### end Alembic commands ###
